version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: aspnetidentity-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: aspnetidentity
      POSTGRES_PASSWORD: aspnetidentity
      POSTGRES_DB: aspnetidentity
    ports:
      - "15432:5432"  # Host port 15432 maps to container port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
